/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        primary: "#ffffff",
        "on-primary": "#000000",
        "accent-blue": "#0099ff",
        ink: "#ffffff",
        "ink-muted": "#999999",
        canvas: "#090909",
        "surface-1": "#141414",
        "surface-2": "#1c1c1c",
        hairline: "#262626",
        "hairline-soft": "#1a1a1a",
        "gradient-magenta": "#d44df0",
        "gradient-violet": "#6a4cf5",
        "gradient-orange": "#ff7a3d",
        "gradient-coral": "#ff5577",
        success: "#22c55e",
      },
      fontFamily: {
        display: ["GT Walsheim Framer Medium", "Inter", "sans-serif"],
        body: ["Inter Variable", "Inter", "sans-serif"],
      },
      fontSize: {
        "display-xxl": ["110px", { lineHeight: "0.85", letterSpacing: "-5.5px", fontWeight: "500" }],
        "display-xl": ["85px", { lineHeight: "0.95", letterSpacing: "-4.25px", fontWeight: "500" }],
        "display-lg": ["62px", { lineHeight: "1.00", letterSpacing: "-3.1px", fontWeight: "500" }],
        "display-md": ["32px", { lineHeight: "1.13", letterSpacing: "-1.0px", fontWeight: "500" }],
        headline: ["22px", { lineHeight: "1.20", letterSpacing: "-0.8px", fontWeight: "700" }],
        subhead: ["24px", { lineHeight: "1.30", letterSpacing: "-0.01px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.30", letterSpacing: "-0.18px", fontWeight: "400" }],
        body: ["15px", { lineHeight: "1.30", letterSpacing: "-0.15px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "1.40", letterSpacing: "-0.14px", fontWeight: "500" }],
        caption: ["13px", { lineHeight: "1.20", letterSpacing: "-0.13px", fontWeight: "500" }],
        micro: ["12px", { lineHeight: "1.20", letterSpacing: "-0.12px", fontWeight: "400" }],
        button: ["14px", { lineHeight: "1.0", letterSpacing: "-0.14px", fontWeight: "500" }],
      },
      borderRadius: {
        xs: "4px",
        sm: "6px",
        md: "10px",
        lg: "15px",
        xl: "20px",
        xxl: "30px",
        pill: "100px",
      },
      spacing: {
        hair: "1px",
        xxs: "4px",
        xs2: "8px",
        sm2: "12px",
        md2: "15px",
        lg2: "20px",
        xl2: "30px",
        xxl2: "40px",
        section: "96px",
      },
    },
  },
  plugins: [],
};
